### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by NoushinN** [bcgov/statscan-taxdata-tidying#13]
@stephhazlitt  and @boshek 
The place where new code has been added is here: https://github.com/bcgov/statscan-taxdata-tidying/blob/1143a80eb3a7f1351a36ee4fe83f9e514cf0ea27/fam-clean.R#L83
Appreciate a review

**Comment by stephhazlitt** [comment]
@NoushinN Was this change only in the family files? Or also the individual files?

**Comment by NoushinN** [comment]
Sorry seems like my attachments aren't being sent: they are also in ind-13 and ind scripts

https://github.com/bcgov/statscan-taxdata-tidying/blob/1143a80eb3a7f1351a36ee4fe83f9e514cf0ea27/ind-clean-13.R#L67



https://github.com/bcgov/statscan-taxdata-tidying/blob/1143a80eb3a7f1351a36ee4fe83f9e514cf0ea27/ind-clean.R#L131
