### ISSUE TITLE
automate column names 

### ISSUE THREAD

**Issue by NoushinN** [bcgov/statscan-taxdata-tidying#2]
The issue with the column headers right now is that there are repeating names within the same table and this may be human error (under investigation).
A better alternative for column names is to automate names: i.e.  concatenate the first 3 rows from original xls files into 1 
An example is:

**Employment income
Number
Males**

Becomes

**Employment income_Number_Males**

**Comment by NoushinN** [comment]
A sample of raw data xlsx and need for column automation
[Sample-Columns.xlsx](https://github.com/bcgov/statscan-taxdata-tidying/files/2958679/Sample-Columns.xlsx)

**Comment by stephhazlitt** [comment]
Using the posted sample data:

```
library(readxl)
library(dplyr)
library(tidyr)
library(stringr)

#url for sample data from GitHub 
sample_rows <- "https://github.com/bcgov/statscan-taxdata-tidying/files/2958679/Sample-Columns.xlsx"


# read in xls data, transpose, concatenate names, pull out character vector

ind_sheet1_colnames <- read_xlsx("Sample-Columns.xlsx", skip = 1, col_names = FALSE) %>%
  t() %>% 
  as_tibble(.name_repair = ~ c("one", "two", "three")) %>% 
  fill(one, two, three) %>%  # fill empty cells
  mutate(sheet1_col_names = paste("Sheet1", one, two, three, sep = '_'),
               sheet1_col_names = str_replace(sheet1_col_names, "_NA_NA", "")) %>% 
  select(sheet1_col_names) %>% 
  pull()
  
# read in sample xls data and use new column names

sheet_data <- read_xlsx("Sample-Columns.xlsx",
                        col_names = ind_sheet1_colnames)
```

**Comment by NoushinN** [comment]
This code works too in order to convert all empty cells to NA

**## convert empty cells to NA**
empty_as_na <- function(x){
    if("factor" %in% class(x)) x <- as.character(x) ## since ifelse wont work with factors
    ifelse(as.character(x)!="", x, NA)
  }

**## transform all columns**
dat1 %>% mutate_each(funs(empty_as_na)) 


In trying to replace NA's with the value to its left, the following runs **but** is not converting..

na.rows <- which( apply(dat1, 1, function(z) (all(is.na(z)) ) ) )
dat1[na.rows , ] <- dat1[na.rows-1, ]

**Comment by NoushinN** [comment]
Thank you @stephhazlitt This is now working perfectly on **real** data tables

```

## load data
path_input_folder <- "~/Data"
path_input_file   <- paste0(path_input_folder,"/","2015_IND_Tables_1_to_13_Canada.xlsx")
dat1 <- read_xlsx(path_input_file, sheet = 1, skip = 1, col_names = FALSE)


```
```
## repair table columns
my_custom_name_repair <- read_xlsx(path_input_file, skip = 1, col_names = FALSE, n_max = 3) %>%
  t() %>% 
  as_tibble(.name_repair = ~ c("one", "two", "three")) %>% 
  fill(one, two, three) %>%  # fill empty cells
  mutate(sheet1_col_names = paste("I-01", one, two, three, sep = '_'),
         sheet1_col_names = str_replace(sheet1_col_names, "_NA_NA|_NA", "")) %>% 
  select(sheet1_col_names) %>% 
  pull()

```
```
## repair column names
my_custom_header_repair <- str_replace_all(as.character(my_custom_name_repair), c(" |/|'|"), "")
```
```
## read in sample xlsx data and use new column names

sheet_data <- read_xlsx(path_input_file,
                        col_names = my_custom_header_repair)
View(sheet_data)

````

**Comment by stephhazlitt** [comment]
[Closed](https://github.com/bcgov/statscan-taxdata-tidying/commit/d0ad0e3530a45178f7b35b2e58675bf141015b74)
