### ISSUE TITLE
Two non-BC area are included

### ISSUE THREAD

**Issue by CindyWang101** [bcgov/statscan-taxdata-tidying#21]
990 (Whitehorse) and 995 (Northwest Territories) are included in the file

**Comment by boshek** [comment]
Also included:

YUKON
WHITEHORSE
NORTHWEST TERRITORIES
YELLOWKNIFE
NUNAVUT

**Comment by stephhazlitt** [comment]
I think these same areas need to be removed from the families tables and individual table 13 as well. Working with the same project design, I think that means porting [this fix](https://github.com/bcgov/statscan-taxdata-tidying/commit/d7ea72f9768ececc5e7a69cafdb458960c816dfc) to the [families](https://github.com/bcgov/statscan-taxdata-tidying/blob/col_classes/fam-clean.R#L73-L82) and [individual table 13 scripts](https://github.com/bcgov/statscan-taxdata-tidying/blob/col_classes/ind-clean-13.R#L57-L66) as well?

**Comment by boshek** [comment]
This is a great point and an easy fix
