### ISSUE TITLE
add table prefix to column names

### ISSUE THREAD

**Issue by NoushinN** [bcgov/statscan-taxdata-tidying#3]
Since the final merged tables are a collection of all Sub-sheets, to make it easy for researchers, we can add a prefix to column headers:
e.g.  **3A_Employment income_Number_Males**

**Comment by stephhazlitt** [comment]
This could be done as part of implementing [issue #2](https://github.com/bcgov/statscan-taxdata-tidying/issues/2)?

**Comment by stephhazlitt** [comment]
[Closed](https://github.com/bcgov/statscan-taxdata-tidying/commit/b735f118f59cd008eb6021ab75423574cfa91284)
