### ISSUE TITLE
separate data folder into "raw" and "derived"

### ISSUE THREAD

**Issue by andkov** [bcgov/statscan-taxdata-tidying#5]
@NoushinN , 

To segregate the input and output of R scripts, consider keeping the data sets in two separate folders. 
 The "raw" folder will host the data in its initial form, while the "derived" data will host the data that emerged from applying manipulation scripts.

**Comment by NoushinN** [comment]
Thank you @andkov, this is implemented now (the new organization is pushed into a branch until further notice).

**Comment by stephhazlitt** [comment]
Nice work @NoushinN. Can we rename these `\raw-data` and `\tidy-data` (or what was initially proposed) &mdash; none of the data is private, it is all under the Statistics Canada Open Licence regardless of format.

**Comment by stephhazlitt** [comment]
[Closed](https://github.com/bcgov/statscan-taxdata-tidying/commit/6e62e7a2b72fb71277b955ed49e73eb410a52d6f)
