### ISSUE TITLE
Create dynamic documentation for manipulation scripts

### ISSUE THREAD

**Issue by andkov** [bcgov/statscan-taxdata-tidying#6]
@NoushinN 

Consider using  `knitr::stitch_rmd()` to produce a dynamic documentation  of each of the manipulation scripts in `./R` folder.   This can be accomplished by inserting the following script at the top of each script

```r
 knitr::stitch_rmd(
   script = "./manipulation/0-greeter.R",
  output = "./manipulation/stitched-output/0-greeter.md"
 )
```
or cycling through all scripts in a dedicated governor (recommended).

**Comment by NoushinN** [comment]
thank you @andkov, great advice, we are going with the government GitHub framework recommendations for R scripts but this is a great tip, I will be implementing it for my scripts going forward

**Comment by andkov** [comment]
Glad to help! Please let me know if you gave the need of creating an annotation later to the report
