### ISSUE TITLE
Use relative paths instead of `setwd()`

### ISSUE THREAD

**Issue by andkov** [bcgov/statscan-taxdata-tidying#7]
@NoushinN 

Typically, the use of `setwd()` is considered a bad practice (see [1](https://stackoverflow.com/questions/13770304/risks-of-using-setwd-in-a-script) , [2](http://plantarum.ca/code/setwd/), [3](https://community.rstudio.com/t/project-oriented-workflow-setwd-rm-list-ls-and-computer-fires/3549) ).  Instead, rely on the properties of the R-project to establish relative paths. 

Thus for example, ( https://github.com/bcgov/statscan-taxdata-tidying/blob/master/R/T1_Taxdata_Final_Merge_FAM_all.R#L16) 
```r
# load folder and files
setwd("~/Data/FAM")
getwd()
dir.wrk <- "~/Data/FAM"
dir.wrk <- getwd()

...

df1 <- read.table(file ="2016_Family_Table.csv",

```
can be re-written as

```r
path_input_folder <- "./Data/FAM"
path_input_file   <- paste0(path_input_folder,"/","2016_Family_Table.csv")
df1               <- read.table(file = path_input_file)
```

However, I would not recommend importing each file individually. Instead, write a regular expression to load the paths to all files in a separate list object, which can be queried dynamically.

**Comment by stephhazlitt** [comment]
Closed with updated approaches, using the here::here() package.
